version: '3'
services:
    app:
        container_name: app
        build: ./.docker/php-fpm
        restart: always
        volumes:
            - .:/var/www
        networks:
            - app-network
    
    nginx:
        container_name: nginx
        build: ./.docker/nginx
        restart: always
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        networks:
            - app-network

    db:
        container_name: db
        build: ./.docker/mysql
        restart: always
        command: --innodb-use-native-aio=0 --character-set-server=utf8
        ports:
            - "3306:3306"
        volumes:
            - ../data/laravel:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        expose:
            - "6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge